mdapi/objects/ltng_M2M_Relationship__c.object
<CustomObject>
    <description>A description of any Many to Many relationship

For example, Account can have many Contacts - just as Contacts can have relationships in many Accounts.
Both of these are linked through a common object: AccountContactRelation (with an Account and Contact lookup)
to link the two together.

This Object would describe that relation, with the object on the left (ex: Account)
the object on the right (ex: Contact)
and the junction object - that relates the two.</description>
    <label>M2M Relationship</label>
    <nameField>
        <label>M2M Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M2M Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>JunctionLeftObjectRelationshipField__c</fullName>
        <inlineHelpText>API Name of the field used to relate the Junction Object to the Left Object</inlineHelpText>
        <label>Junction Left Object Relationship Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JunctionRightObjectRelationshipField__c</fullName>
        <inlineHelpText>API Name of the field used to relate the Junction Object to the Right Object</inlineHelpText>
        <label>Junction Right Object Relationship Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeftObjectAPIName__c</fullName>
        <inlineHelpText>The API Name of an object in a many to many relationship</inlineHelpText>
        <label>Left Object API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeftObjectSpecificFields__c</fullName>
        <inlineHelpText>The individual fields to show if the compact layout is not shown.
(Note, the record is not shown if not using compact layout and no fields selected)</inlineHelpText>
        <label>Left Object Specific Fields</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LeftObjectUsesCompactLayout__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If checked and looking at the &quot;Left Object&quot; in the relationship, then the compact layout is shown.</inlineHelpText>
        <label>Left Object Uses Compact Layout</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RightObjectAPIName__c</fullName>
        <inlineHelpText>The API Name of an object in a many to many relationship</inlineHelpText>
        <label>Right Object API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RightObjectSpecificFields__c</fullName>
        <inlineHelpText>The individual fields to show if the compact layout is not shown.
(Note, the record is not shown if not using compact layout and no fields selected)</inlineHelpText>
        <label>Right Object Specific Fields</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RightObjectUsesCompactLayout__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If checked and looking at the &quot;Right Object&quot; in the relationship, then the compact layout is shown.</inlineHelpText>
        <label>Right Object Uses Compact Layout</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

dx/force-app/main/default/classes/ltng_AdvManyToManyUtil.cls
/**
 * Utility class for dealing with Many to Many Relationships.
 * @class ltng_AdvManyToManyUtil
 **/
public with sharing class ltng_AdvManyToManyUtil {
    
    /** represents no selection **/
    public static final String NO_SELECTION = '-No Selection-';
    public static final String NO_SELECTION_VALUE = '';

    //--    -   -   -   -   -   -   -   -   -   -   -   -   -   -   -
    //-- Methods for describing Relationships and Objects
    //--    -   -   -   -   -   -   -   -   -   -   -   -   -   -   -

    /**
     * Given a record id, determines the SObject Describe of the record.
     * @param recordId (Id)
     * @return Schema.DescribeSObjectResult
     */
    public static Schema.DescribeSObjectResult getSObjectDescription(Id recordId){
        Schema.SObjectType objectType = recordId.getSObjectType();
        return objectType.getDescribe();
    }

    /**
     * Given an SObject Name, return the Describe of that SObject
     * @param sObjectName (String)
     * @return Schema.DescribeSObjectResult
     **/
    public static Schema.DescribeSObjectResult getSobjectDescription(String sObjectName){
        Schema.DescribeSObjectResult[] resultList = Schema.describeSObjects(new String[]{sObjectName});
        return resultList[0];
    }

    /**
     * Orients a relationship so on a many to many relationship,
     * a given SObject type is on the left.
     * @param relationship (ltng_M2M_Relationship__c) - a Many to Many Relationship (with an object on a left, right and junction between)
     * @param sObjectApiName (String) - the object we want on the left of the relationship
     * @return updated relationship
      */
    public static ltng_M2M_Relationship__c orientRelationship(ltng_M2M_Relationship__c relationship, String sObjectApiName){
        ltng_M2M_Relationship__c results;
        ltng_M2M_Relationship__c relationshipClone;

        if (relationship.LeftObjectAPIName__c.equalsIgnoreCase(sObjectApiName)) {
            results = relationship;
        } else {
            System.debug('relationship is out of alignment');
            results = flipRelationship(relationship);
        }

        return results;
    }

    /**
     * Determines if the same object is used on both the left and right of the relationship.
     * <p>It is a many to many relationship on the same object</p>
     * @param relationship (ltng_M2M_Relationship__c)
     * @return (Boolean)
     */
    public static Boolean isReflectiveRelationship(ltng_M2M_Relationship__c relationship){
        Boolean results = false;

        if (relationship != null) {
            if (relationship.LeftObjectAPIName__c == relationship.RightObjectAPIName__c) {
                results = true;
            } else {
                results = (
                    relationship.LeftObjectApiName__c != null &&
                    relationship.LeftObjectAPIName__c.equals(relationship.RightObjectAPIName__c)
                );
            }
        }

        return results;
    }

    /**
     * Flips the relationship between the left and right sides.
     * <p>Thinking about a many to many relationship, we have Opportunities and Products
     * with OpportunityProducts as the junction object.</p>
     * <p>Whether Opportunities is considered the 'left' or the 'right'
     *  - doesn't make much difference. So this method allows for swapping them</p>
     * @param relationship (ltng_M2M_Relationship__c) - a Many to Many Relationship to be switched.
     * @return ltng_M2M_Relationship__c - the flipped relation.
     **/
    public static ltng_M2M_Relationship__c flipRelationship(ltng_M2M_Relationship__c relationship){
        ltng_M2M_Relationship__c relationshipClone;

        relationshipClone = relationship.clone(false, false, false, false);
        System.debug('relationshipClone'); System.debug(relationshipClone);

        relationship.LeftObjectAPIName__c = relationshipClone.RightObjectAPIName__c;
        relationship.JunctionLeftObjectRelationshipField__c = relationshipClone.JunctionRightObjectRelationshipField__c;
        relationship.LeftObjectUsesCompactLayout__c = relationshipClone.RightObjectUsesCompactLayout__c;
        relationship.LeftObjectSpecificFields__c = relationshipClone.RightObjectSpecificFields__c;

        relationship.RightObjectAPIName__c = relationshipClone.LeftObjectAPIName__c;
        relationship.JunctionRightObjectRelationshipField__c = relationshipClone.JunctionLeftObjectRelationshipField__c;
        relationship.RightObjectUsesCompactLayout__c = relationshipClone.LeftObjectUsesCompactLayout__c;
        relationship.RightObjectSpecificFields__c = relationshipClone.LeftObjectSpecificFields__c;

        return relationship;
    }

    //--    -   -   -   -   -   -   -   -   -   -   -   -   -   -   -
    //-- Internal Classes used for communication
    //--    -   -   -   -   -   -   -   -   -   -   -   -   -   -   -

    /**
     * Represents an Api entity - with a name and an API identifier.
     * <p>Used by the Relation Editor when showing Objects and fields
     * available for selection</p>
     */
    public virtual class ApiOption {
        @AuraEnabled
        public String optionLabel;

        @AuraEnabled
        public String optionApiName;

        public ApiOption(){
            this(NO_SELECTION, NO_SELECTION_VALUE);
        }

        public ApiOption(String label, String apiName){
            this.optionLabel = label;
            this.optionApiName = apiName;
        }
    }
}